###! CORE SYSTEM DIRECTIVES
# High-level operational state of the entire monitoring stack.
# "auto"   : [Recommended] Enables Dynamic Moving Average (DMA) logic.
# "manual" : Fallback to hard-coded industrial safety standards.
mode = "auto"

##! ADAPTIVE LOGIC KERNELS (ALGORITHM BRAIN)
# Parameters governing the session-based learning behavior.

#! COMPUTATIONAL INSTRUCTION: 
#! DYNAMIC_THRESHOLD = (Σ Temp[window_size] / window_size) + temp_offset
temp_offset = 10

#! SLIDING WINDOW: Number of samples (2s each) for Moving Average calculation.
# 30 samples = 60-second observation window.
window_size = 10

#! HYSTERESIS: Anti-flicker buffer in Degrees Celsius.
# Prevents state oscillation when temp floats exactly at threshold.
hysteresis = 2
# If the new fire reignites within X seconds after being extinguished → it will be included in the old incident.
incident_cooldown = 60

# ---------------------------------------------------------

###! STATIC FALLBACK & EMERGENCY LIMITS
# Used as explicit limits in "manual" mode or as cold-start fallbacks.
[threshold.default]

# Temperature threshold in Degrees Celsius.
# Set to 45°C to sit above extreme summer ambient (e.g., El Niño ~42°C).
temp = 45

# Smoke density (MQ-2 Raw ADC).
# Normal air: 80-150. Fire density: >300.
smoke = 300

# ---------------------------------------------------------

###! UI RENDERER CONTEXT (SERVER-DRIVEN)
# Graphics parameters for the Backend-generated SVG engine.
[ui.graph]
temp_scale_max = 70
smoke_scale_max = 1023
width = 800
height = 200
max_points = 50
stroke_color = "#ff3d00"
fill_opacity = 0.1
